included:
  - RandomUser
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
function_parameter_count:
 - 10
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 400
  error: 800
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
